---
- name: Setup proxy variables for shells
  template:
    src: outboundproxy.sh.j2
    dest: /etc/profile.d/outboundproxy.sh
    owner: root
    group: root
    mode: 0644

- name: Create directory for systemd global service supplementary config
  file:
    path: /etc/systemd/system.conf.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Setup proxy variables for systemd
  template:
    src: outboundproxy.systemd.conf.j2
    dest: /etc/systemd/system.conf.d/10-outboundproxy.conf
    owner: root
    group: root
    mode: 0644
  notify: reinit systemd

- name: Set up proxy config for yum.
  lineinfile:
    insertafter: "[main]"
    line: "proxy=http://{{ proxy.host }}:{{ proxy.port }}"
    path: /etc/yum.conf
    state: present

- meta: flush_handlers
